### ISSUE TITLE
Panic on unsupported operation: automatic sidecar injection

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-app-mesh#49]
#### Current Behavior
Panicked when "Automatic sidecar injection" operation was run from Meshery UI.

```
➜  meshery-app-mesh git:(master) make run
DEBUG=true go run main.go
INFO[2021-10-18T18:19:30-05:00] Adaptor Listening at port: 10005              app=app-mesh-adapter
INFO[2021-10-18T18:22:11-05:00] Creating instance                             app=app-mesh-adapter
INFO[2021-10-18T18:22:11-05:00] Listing Operations                            app=app-mesh-adapter
INFO[2021-10-18T18:22:11-05:00] Creating instance                             app=app-mesh-adapter
INFO[2021-10-18T18:22:17-05:00] Creating instance                             app=app-mesh-adapter
INFO[2021-10-18T18:23:03-05:00] Creating instance                             app=app-mesh-adapter
INFO[2021-10-18T18:23:03-05:00] Applying operation label-namespace            app=app-mesh-adapter
panic: interface conversion: error is *errors.StatusError, not *errors.Error

goroutine 33 [running]:
github.com/layer5io/meshkit/errors.GetCode(0x5fbd600, 0xc000796a00, 0x0, 0x0)
	/Users/lee/code/go/pkg/mod/github.com/layer5io/meshkit@v0.2.31/errors/errors.go:90 +0xd1
github.com/layer5io/meshkit/logger.(*Logger).Error(0xc000134088, 0x5fbd600, 0xc000796a00)
	/Users/lee/code/go/pkg/mod/github.com/layer5io/meshkit@v0.2.31/logger/logger.go:57 +0xaa
github.com/layer5io/meshery-adapter-library/adapter.(*Adapter).StreamErr(...)
	/Users/lee/code/go/pkg/mod/github.com/layer5io/meshery-adapter-library@v0.1.24/adapter/stream.go:25
github.com/layer5io/meshery-app-mesh/app_mesh.(*AppMesh).ApplyOperation.func3(0xc0005a6060, 0xf, 0xc0005a6070, 0xe, 0xc0005a6058, 0x8, 0x0, 0x0, 0x0, 0xc0005dc030, ...)
	/Users/lee/code/meshery-app-mesh/app_mesh/app_mesh.go:94 +0x199
created by github.com/layer5io/meshery-app-mesh/app_mesh.(*AppMesh).ApplyOperation
	/Users/lee/code/meshery-app-mesh/app_mesh/app_mesh.go:85 +0x565
exit status 2
make: *** [run] Error 1
```

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@Shreyas220 @DelusionalOptimist fyi

**Comment by Shreyas220** [comment]
> @Shreyas220 @DelusionalOptimist fyi

faced this problem in istio as well, for not using meshkit style errors
